version: 2
updates:
- package-ecosystem: elm
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
- package-ecosystem: elm
  directory: "/benchmarks/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
- package-ecosystem: elm
  directory: "/examples"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
- package-ecosystem: elm
  directory: "/review/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
